#!/usr/bin/env julia
# Generate the committed ITER regression fixture for ALPHA (test/fixtures/iter_tjlfep.txt).
#
# Provenance: FUSE :ITER sample case -> TJLFEP.runTHD critical gradients. This script
# needs an environment with FUSE + TJLFEP + IMAS (e.g. the TJLFEP project); ALPHA itself
# is NOT required here. The fixture freezes the ITER background profiles (exactly as
# ALPHA's AlphaInput(dd, rho) extracts them) together with the TJLFEP dndr_crit/dpdr_crit
# on the full core_profiles rho_tor_norm grid, so the regression test is reproducible
# from just the committed text file (no FUSE/TJLFEP at test time).
#
# Run (from the TJLFEP package dir):
#   module load julia/1.11.7 && export JULIA_DEPOT_PATH=$PSCRATCH/.julia
#   julia --project=. /path/to/ALPHA/test/fixtures/generate_iter_fixture.jl
ENV["TJLFEP_FILE_ONLY"] = "0"

import FUSE
import IMAS
using TJLFEP
using Printf

# clamped piecewise-linear interp (mirror of ALPHA._interp)
function _interp(x, y, xq)
    n = length(x)
    out = similar(collect(float.(xq)))
    for (k, q) in enumerate(xq)
        if q <= x[1]
            out[k] = y[1]
        elseif q >= x[n]
            out[k] = y[n]
        else
            j = searchsortedlast(x, q)
            j = clamp(j, 1, n - 1)
            t = (q - x[j]) / (x[j+1] - x[j])
            out[k] = y[j] * (1 - t) + y[j+1] * t
        end
    end
    return out
end

println("=== building ITER dd ===")
ini, act = FUSE.case_parameters(:ITER; init_from=:ods)
ini.core_profiles.ngrid = 201
dd = IMAS.dd()
FUSE.init(dd, ini, act)

# --- background profiles, exactly as AlphaInput(dd, rho_full) would extract them ---
cp1d = dd.core_profiles.profiles_1d[]
rho_full = collect(cp1d.grid.rho_tor_norm)
ne = collect(cp1d.electrons.density_thermal) ./ 1e19
Te = collect(cp1d.electrons.temperature) ./ 1e3
ion = cp1d.ion[1]
Ti = collect(ion.temperature) ./ 1e3
ni = collect(ion.density_thermal) ./ 1e19

eqt1d = dd.equilibrium.time_slice[].profiles_1d
rho_eq = collect(eqt1d.rho_tor_norm)
rmin_eq = (collect(eqt1d.r_outboard) .- collect(eqt1d.r_inboard)) ./ 2
Rmaj_eq = (collect(eqt1d.r_inboard) .+ collect(eqt1d.r_outboard)) ./ 2
vol_eq = collect(eqt1d.volume)
rmin = _interp(rho_eq, rmin_eq, rho_full)
volume = _interp(rho_eq, vol_eq, rho_full)
Rmaj = _interp(rho_eq, Rmaj_eq, rho_full)

# --- TJLFEP TGLF-EP scan -> critical gradients on the full grid ---
SCAN_N = 6
rho_scan = collect(range(0.2, 0.9; length=SCAN_N))
OptionsDict = Dict{String,Any}(
    "nn" => 5, "nr" => 201, "jtscale_max" => 1, "nmodes" => 4, "PROCESS_IN" => 5,
    "THRESHOLD_FLAG" => 0, "N_BASIS" => 2, "SCAN_METHOD" => 1,
    "REJECT_I_PINCH_FLAG" => 0, "REJECT_E_PINCH_FLAG" => 0, "REJECT_TH_PINCH_FLAG" => 1,
    "REJECT_EP_PINCH_FLAG" => 0, "REJECT_TEARING_FLAG" => 1, "ROTATIONAL_SUPPRESSION_FLAG" => 1,
    "QL_RATIO_THRESH" => 0.001, "THETA_SQ_THRESH" => 100.0, "Q_SCALE" => 1.0,
    "WRITE_WAVEFUNCTION" => 0, "KY_MODEL" => 2, "SCAN_N" => SCAN_N, "IRS" => 2,
    "FACTOR_IN_PROFILE" => false, "FACTOR_IN" => 1.0, "WIDTH_IN_FLAG" => false,
    "WIDTH_MIN" => 1.0, "WIDTH_MAX" => 2.0, "INPUT_PROFILE_METHOD" => 2,
    "N_ION" => 3, "IS_EP" => 3, "REAL_FREQ" => 1)

println("=== TJLFEP runTHD (CPU, SCAN_N=$SCAN_N) ===")
outdir = mktempdir()
_, _, SFmin, dpdr_crit, dndr_crit = cd(outdir) do
    runTHD(dd, rho_scan, OptionsDict; printout=true, saveFiles=false, dir=outdir, use_gpu=false)
end
@printf("SFmin = %s\n", SFmin)

cols = (rho_full, rmin, ne, Te, Ti, ni, volume, Rmaj, dndr_crit, dpdr_crit)
@assert all(==(length(rho_full)), length.(cols)) "column length mismatch"

fixture = joinpath(@__DIR__, "iter_tjlfep.txt")
open(fixture, "w") do io
    println(io, "# ITER (FUSE :ITER) background profiles + TJLFEP critical gradients.")
    println(io, "# Generated by generate_iter_fixture.jl. Units: ne,ni[1e19 m^-3] Te,Ti[keV] rmin,Rmaj[m] volume[m^3].")
    println(io, "# rho rmin ne Te Ti ni volume Rmaj dndr_crit dpdr_crit")
    for i in eachindex(rho_full)
        @printf(io, "%.10e %.10e %.10e %.10e %.10e %.10e %.10e %.10e %.10e %.10e\n",
            rho_full[i], rmin[i], ne[i], Te[i], Ti[i], ni[i], volume[i], Rmaj[i], dndr_crit[i], dpdr_crit[i])
    end
end
@printf("wrote %s (%d rows)\n", fixture, length(rho_full))
